### ISSUE TITLE
TypeError: Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#116]
Seen in the logs over a long time span.  Doesn't happen often.

    Trace: TypeError: Cannot read property 'role' of undefined
        at app.post (/app/backend/routes/auth.js:159:30)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Shop.findOne.then (/app/backend/routes/_auth.js:54:7)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:126:23)
        at app.use (/app/backend/app.js:151:11)
        at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
        at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
        at /app/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at next (/app/node_modules/express/lib/router/route.js:127:14)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:97:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Shop.findOne.then (/app/backend/routes/_auth.js:54:7)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)

**Comment by nick** [comment]
Should be fixed in latest prod release
