### ISSUE TITLE
AutoSSL priming logging errors that aren't errors

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#163]
Seen this on a recent test:

    Trace: { Error: self signed certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
        at TLSSocket.emit (events.js:198:13)
        at TLSSocket.EventEmitter.emit (domain.js:448:20)
        at TLSSocket._finishInit (_tls_wrap.js:666:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
        at ClientRequest.https.get.on (/app/backend/utils/http.js:22:17)
        at ClientRequest.emit (events.js:198:13)
        at ClientRequest.EventEmitter.emit (domain.js:448:20)
        at TLSSocket.socketErrorListener (_http_client.js:401:9)
        at TLSSocket.emit (events.js:198:13)
        at TLSSocket.EventEmitter.emit (domain.js:448:20)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    [ERROR] dshop.utils.http: Error GETting mikes-swag.shopwithslice.com/
    [INFO]  dshop.utils.deployShop: Error when attempting to trigger AutoSSL on attempt 1: { Error: self signed certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
        at TLSSocket.emit (events.js:198:13)
        at TLSSocket.EventEmitter.emit (domain.js:448:20)
        at TLSSocket._finishInit (_tls_wrap.js:666:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }

That probably shouldn't be an error.  This is reasonably expected to happen and should be a warning at most.

**Comment by franckc** [comment]
@mikeshultz This is fixed, right? Closing. Feel free to re-open if I'm wrong.
