### ISSUE TITLE
Error making stripe test payment

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#165]
Seen when trying to test stripe payments:

    [INFO]  dshop.routes.stripe: Trying to make payment...
    (node:30) UnhandledPromiseRejectionWarning: Error: The statement descriptor cannot include '
        at Function.generate (/app/node_modules/stripe/lib/Error.js:39:16)
        at IncomingMessage.res.once (/app/node_modules/stripe/lib/StripeResource.js:175:33)
        at Object.onceWrapper (events.js:286:20)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Request data:

    {
        "amount":2450,
        "data":"QmXp5JQzGpkm8gmqVC5TLKs1BqZyfLRHqu2Ey9nxaxMFTM",
        "listingId":"4-001-82"
    }

Probably related:

https://github.com/OriginProtocol/dshop/blob/9cbd2f5f9ae36b31e21f19398101cca68b87a1f5/backend/routes/stripe.js#L45

Shop name is "Mike's Swag"

**Comment by mikeshultz** [comment]
Fixed with 8378d8218e3691417f2808f3ef7ebab19eb55dd2.

CC @nick
