### ISSUE TITLE
Error in the back-end when sending order confirmation email

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#173]
Saw this error in the back-end after I placed an order and paid in crypto:
```
[INFO]  dshop.utils.handleLog: Event OfferCreated for listing Id 1-001-2389
[INFO]  dshop.utils.handleLog: OfferCreated - 0 by 0x5b2A5d1AB8a5B83C0f22cB1Df372d23946aA7d8F
[INFO]  dshop.utils.handleLog: IPFS Hash: QmYYREXauBDqEiu6RiHUqpWteS3xP1V83Jis1hPj2Ynvoi
[INFO]  dshop.utils.handleLog: Saved order 1-001-2389-0 to DB.
(node:30) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at sendNewOrderEmail (/app/backend/utils/emailer.js:110:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by franckc** [comment]
Fix by @nick in commit 784471a8070559962bbddfbb55881e3b8d5291ce
