### ISSUE TITLE
emailer error seen in backend

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#174]
Seen on mainnet backend recently:

    (node:30) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
        at sendNewOrderEmail (/app/backend/utils/emailer.js:110:24)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This code line number appears to be before 008f94277ba8bd11803965a7ca71dcc6b5e324fc by @shahthepro.  Perhaps that fixed this?

**Comment by mikeshultz** [comment]
Duplicate of #173
