### ISSUE TITLE
Error in the /orders/:orderId/printful route

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#191]
Seen in production logs:
```
2020-07-09T18:53:32.07128737Z (node:30) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: fulfilled
2020-07-09T18:53:32.071349857Z     at ServerResponse.writeHead (_http_server.js:211:11)
2020-07-09T18:53:32.071358085Z     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26)
2020-07-09T18:53:32.071380666Z     at ServerResponse._implicitHeader (_http_server.js:202:8)
2020-07-09T18:53:32.071385096Z     at write_ (_http_outgoing.js:585:9)
2020-07-09T18:53:32.071388997Z     at ServerResponse.write (_http_outgoing.js:567:10)
2020-07-09T18:53:32.071392684Z     at writetop (/app/node_modules/express-session/index.js:291:26)
2020-07-09T18:53:32.071396393Z     at ServerResponse.end (/app/node_modules/express-session/index.js:339:16)
2020-07-09T18:53:32.071400254Z     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
2020-07-09T18:53:32.07140397Z     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
2020-07-09T18:53:32.07140773Z     at ServerResponse.send (/app/node_modules/express/lib/response.js:158:21)
2020-07-09T18:53:32.071411453Z     at app.get (/app/backend/routes/printful.js:23:40)
2020-07-09T18:53:32.071415271Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by franckc** [comment]
This seems to be because fetchOrder returns 'fulfilled' rather than an HTTP status code.
See code here: https://github.com/OriginProtocol/dshop/blob/master/backend/routes/printful.js#L25

**Comment by franckc** [comment]
Fixed and verified fix in prod. Closing.
