### ISSUE TITLE
[Orders] Metamask error when finalizing a crypto offer

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#245]
Kay ran into the following error while trying to finalize an order paird with crypto from the admin Orders page.

```
"BigNumber Error: new BigNumber() not a number: null
    at Q (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:800541)
    at A (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:806026)
    at new V (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:798446)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3210034)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3210093)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3210134)
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3210238)
    at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3210953)
..."
```

**Comment by franckc** [comment]
I was not able to reproduce it on my own test shop.
A made an offer in crypto and was able to accept it then finalize it on the merchants admin Orders page.

@kayyoo23 During the next round of testing, do you mind retrying this scenario? Please do make sure to publish your shop before trying (otherwise it will still be using the old code).

**Comment by kayyoo23** [comment]
> I was not able to reproduce it on my own test shop.
> A made an offer in crypto and was able to accept it then finalize it on the merchants admin Orders page.
> 
> @kayyoo23 During the next round of testing, do you mind retrying this scenario? Please do make sure to publish your shop before trying (otherwise it will still be using the old code).

yep will certainly do @franckc

**Comment by franckc** [comment]
Closing this since no new instance of this issue have ben reported in the last 5 days.
