### ISSUE TITLE
Webhook error 

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#307]
Seen in prod:

    [ERROR] dshop.routes.stripe: Error parsing body:  SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
        at handleWebhook (/app/backend/routes/stripe.js:71:19)
        at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
        at /app/node_modules/express-promise-router/lib/express-promise-router.js:58:5
        at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
        at /app/node_modules/express-promise-router/lib/express-promise-router.js:58:5
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at rawParser (/app/node_modules/body-parser/lib/types/raw.js:67:7)
        at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
        at /app/node_modules/express-promise-router/lib/express-promise-router.js:58:5
        at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
        at /app/node_modules/express-promise-router/lib/express-promise-router.js:58:5
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at /app/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
        at router (/app/node_modules/express/lib/router/index.js:47:12)

Possible dupe of #298

**Comment by mikeshultz** [comment]
lol, this was actually me testing with a bodyless request.  It should be handled nicer in #311 but it isn't an existing user error.
