### ISSUE TITLE
Webhook SQL error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#310]
Seen in prod:

    [ERROR] dshop.routes.stripe: Error parsing body:  Error: WHERE parameter "id" has invalid "undefined" value
        at PostgresQueryGenerator.whereItemQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:13)
        at Utils.getComplexKeys.forEach.prop (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25)
        at Array.forEach (<anonymous>)
        at PostgresQueryGenerator.whereItemsQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
        at PostgresQueryGenerator.getWhereConditions (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
        at PostgresQueryGenerator.selectQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
        at QueryInterface.select (/app/node_modules/sequelize/lib/query-interface.js:1127:27)
        at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:1759:34)
        at bound (domain.js:402:14)
        at runBound (domain.js:415:12)
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
        at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)

Rel #307

**Comment by mikeshultz** [comment]
Error handled in #311 and duplicate of #298
