### ISSUE TITLE
UI: Enforce Web3 private key are 0x prefixed

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#313]
Seen when testing on staging with my own shop.  I'm not sure if this effects any other shoop:

    [ERROR] dshop.offerProcessor: Offer creation for shop 11 failed: { Error: invalid hexlify value (argument="value", value="[non-0x-prefixed-hex-string]", code=INVALID_ARGUMENT, version=bytes/5.0.3)
        at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
        at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
        at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:191:21)
        at Object.hexlify (/app/node_modules/@ethersproject/bytes/lib/index.js:189:19)
        at new SigningKey (/app/node_modules/@ethersproject/signing-key/lib/index.js:19:65)
        at new Wallet (/app/node_modules/@ethersproject/wallet/lib/index.js:78:36)
        at Queue.processor (/app/backend/queues/makeOfferProcessor.js:99:20)
        at process._tickCallback (internal/process/next_tick.js:68:7)
      reason: 'invalid hexlify value',
      code: 'INVALID_ARGUMENT',
      argument: 'value',
      value:
       '[non-0x-prefixed-hex-string]' }

Appears to be because my privkey was not prefixed with `0x`

@franckc possibly related to our move to ethers.js?

**Comment by franckc** [comment]
@mikeshultz Yes it must be related. Let me look. Thanks for catching this!!!

**Comment by franckc** [comment]
I checked in prod and no merchant have actually set a web3pk on their own!
```
node configCli.js --networkId=1 --allShops --operation=get --key=web3Pk
```

All the merchants that do have a pk were setup by our team and we are using a 0x prefixed pk for those.

We should still have a check in place in the front-end to prevent entering a non 0x prefixed key.
I'm lowering this issue to a P2 though. Also editing the title for clarity.

**Comment by franckc** [comment]
As a note, on staging, only shop "Mike's Swag Shooop" (id 11) has a non 0x prefixed pk.
