### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#344]
Seen in prod:
```
07-31T00:08:18.676689404Z [INFO]  dshop.utils.deployShop: Shop 114: Preparing data for deploy...
2020-07-31T00:08:20.380949333Z [INFO]  dshop.utils.deployShop: Pinata configured. Adding to the list of pinners.
2020-07-31T00:08:20.381899834Z [INFO]  dshop.utils.deployShop: 📦  Calculating size of /data/dshop-cache/mainnet/celyn/public…
2020-07-31T00:08:20.405855423Z [INFO]  dshop.utils.deployShop: 🚚  Directory /data/dshop-cache/mainnet/celyn/public weighs 10.4 MiB.
2020-07-31T00:08:20.406436513Z [INFO]  dshop.utils.deployShop: 📠  Uploading and pinning to Pinata…
... unrelated logs
2020-07-31T00:09:21.532294637Z This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2020-07-31T00:09:21.532395281Z Error: Request failed with status code 504
2020-07-31T00:09:21.532416039Z     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
2020-07-31T00:09:21.532425391Z     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
2020-07-31T00:09:21.532432322Z     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
2020-07-31T00:09:21.532449452Z     at IncomingMessage.emit (events.js:203:15)
2020-07-31T00:09:21.532456849Z     at IncomingMessage.EventEmitter.emit (domain.js:466:23)
... unrelated logs
2020-07-31T00:16:12.415287781Z [INFO]  dshop.routes.shops: Shop 114 - Saving config
2020-07-31T00:16:12.430397393Z [INFO]  dshop.routes.shops: Shop 114 - Saving config in the DB.
2020-07-31T00:16:18.197890493Z [DEBUG] dshop.listener: WS ping.
2020-07-31T00:16:28.416067802Z [DEBUG] dshop.listener: New block 10564071 timestamp: 1596154556
2020-07-31T00:16:36.835389927Z [DEBUG] dshop.listener: New block 10564072 timestamp: 1596154584
2020-07-31T00:16:37.753991935Z [ERROR] dshop.utils.deployShop: Shop 114: concurrent deployment running. Can not start a new deploy.
```

**Comment by franckc** [comment]
See associated row in the shop_deployments table, id 276

**Comment by mikeshultz** [comment]
This is bound to occur on occasion.  For now, the user is alerted and they can redeploy.  Not sure this warrants being a P1.  Though I do think it's another +1 in favor of async deployments.

**Comment by franckc** [comment]
My guess is that this exception comes from calling this method:
https://github.com/OriginProtocol/dshop/blob/master/backend/utils/deployShop.js#L233

It's part of the ipfs-deploy package and that uses axios to call Pinata.
See this [code](https://github.com/ipfs-shipyard/ipfs-deploy/blob/master/src/pinners/pinata.js#L43).
Sadly it does not seem that package has great error handling/logging so it's hard to tell why the API call to Pinata is timing out... Based on the logs timestamp, it does appear to be a 60sec timeout on the Pinata side.

Looking at the initial small dataset from the DB, it's a pretty high failure rate though. 2 failures out of 29 deploy = 7%.
```select count(*), status from shop_deployments where id > 271 group by status;```

**Comment by mikeshultz** [comment]
It's a 504 from Pinata.  There's nothing we can do to look behind that.  There's nothing ipfs-deploy could add to make this any more informative.

If we see a lot of these, we should bring it up with Pinata but I'm not sure this warrants any more attention right now.  The numbers are now 2 of 79.

**Comment by franckc** [comment]
Just checked and we are not at 2 failures out of 104 since public launch.
```
dshop=> select count(*), status from shop_deployments where created_at > '2020-07-30 23:00+00' group by status;
 count | status  
-------+---------
     2 | Failure
   104 | Success
```

**Comment by franckc** [comment]
This is still happening at a rate of about 1% of deploys. For example in the last 14 days:
```
dshop=> select count(*), status from shop_deployments where created_at > '2020-09-11' group by status;
 count | status  
-------+---------
     5 | Failure
   346 | Success
```

**Comment by mikeshultz** [comment]
The specific error for this issue hasn't been seen in recent history.  I'm gonna close this and open #810 for general investigation into deployment errors.
