### ISSUE TITLE
Error serving static content

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#38]
Seen when loading super admin:

    TypeError: Cannot read property 'length' of null
        at SendStream.hasTrailingSlash (/app/node_modules/send/index.js:304:30)
        at SendStream.pipe (/app/node_modules/send/index.js:590:34)
        at serveStatic (/app/node_modules/serve-static/index.js:125:12)
        at app.get (/app/backend/app.js:140:19)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at /app/node_modules/express/lib/router/index.js:281:22
        at param (/app/node_modules/express/lib/router/index.js:354:14)
        at param (/app/node_modules/express/lib/router/index.js:365:14)
        at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
        at next (/app/node_modules/express/lib/router/index.js:275:10)
        at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
        at SendStream.emit (events.js:198:13)
        at SendStream.EventEmitter.emit (domain.js:448:20)
        at SendStream.error (/app/node_modules/send/index.js:270:17)
        at SendStream.onStatError (/app/node_modules/send/index.js:421:12)
        at onstat (/app/node_modules/send/index.js:726:26)
        at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by nick** [comment]
Should be fixed now
