### ISSUE TITLE
Backend error when fetching config 

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#43]
Seen when trying to checkout with crypto:

    { FetchError: request to https://single-product/single-product/config.json failed, reason: getaddrinfo ENOTFOUND single-product single-product:443
        at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1455:11)
        at ClientRequest.emit (events.js:198:13)
        at ClientRequest.EventEmitter.emit (domain.js:448:20)
        at TLSSocket.socketErrorListener (_http_client.js:401:9)
        at TLSSocket.emit (events.js:198:13)
        at TLSSocket.EventEmitter.emit (domain.js:448:20)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)
      message:
       'request to https://single-product/single-product/config.json failed, reason: getaddrinfo ENOTFOUND single-product single-product:443',
      type: 'system',
      errno: 'ENOTFOUND',
      code: 'ENOTFOUND' }

Shop was created & configured with the super-admin.  Domain should have been single-product.example.com

**Comment by franckc** [comment]
@mikeshultz Is this still happening on the most recent codebase?

**Comment by nick** [comment]
I think this is fixed now
