### ISSUE TITLE
Failed jobs in the makeOffer queue for shop free-land.ogn.app

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#575]
There are 4 jobs (id 279, 280, 281, 282) that are currently failing the the makeOffer queue for shop https://free-land.ogn.app/free-land/

The stacktrace is as follow:
```
Failed shop config from https://free-land.ogn.app/free-land/
Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: Failed shop config from https://free-land.ogn.app/free-land/
    at resolveIPFSGateway (/app/backend/utils/_ipfs.js:33:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by franckc** [comment]
I'll take a look.

CC @gullible1 as a FYI in case the merchant contacts us to inquire about these orders.

**Comment by franckc** [comment]
Looks like the issue is that the merchant hasn't published their shop yet. I suspect they used the "Preview" of their store to test some orders. Then the back-end fails processing the orders when it tries to fetch config.json from the data URL.

We should probably warn the merchant about not trying to do test purchases while in preview mode, and certainly not when the shop has never been published?
An alternative could be to rework the way the back-end fetches config.json so that it either relies on the on-disk version in the cache or from data stored in the DB.

CC @nick in case he has any thoughts on this.

**Comment by franckc** [comment]
Lowering the priority since we haven't had any new instance of this in the last 3 weeks.
