### ISSUE TITLE
Handle Pinata 429s

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#812]
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
    Error: Request failed with status code 429
        at createError (/app/node_modules/ipfs-deploy/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/app/node_modules/ipfs-deploy/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/app/node_modules/ipfs-deploy/node_modules/axios/lib/adapters/http.js:236:11)
        at IncomingMessage.emit (events.js:327:22)
        at IncomingMessage.EventEmitter.emit (domain.js:486:12)
        at endReadableNT (_stream_readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)

There's 2 parts to this.  

1) This error was unhandled and was not reported.  Deploy ended up being expired later by the user retrying deployment repeatedly.
2) A 429 should be dealt with and retried.  This may require changes to ipfs-deploy.

Found 12 other expired deployments that could be related.  I've only spot checked the one so far.

**Comment by micahalcorn** [comment]
Blocked by https://github.com/ipfs-shipyard/ipfs-deploy/pull/192 😐
