### ISSUE TITLE
Orders failing processing due to "Request path contains unescaped characters"

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#839]
We have 5 items in the makeOffer queue that are failing to get processed in prod due to the following error:

```
Request path contains unescaped characters
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at Object.request (https.js:313:10)
    at Object.wrappedHandler (/app/node_modules/@sentry/node/dist/integrations/http.js:78:18)
    at /app/node_modules/agent-base/patch-core.js:25:22
    at /app/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
    at readProductDataFromWeb (/app/backend/logic/products/index.js:130:21)
    at validateOfferData (/app/backend/logic/order/index.js:141:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async processNewOrder (/app/backend/logic/order/index.js:282:23)
    at async _makeOffchainOffer (/app/backend/queues/makeOfferProcessor.js:239:17)
    at async Queue.processor (/app/backend/queues/makeOfferProcessor.js:323:16)TypeError 
```

**Comment by franckc** [comment]
I suspect the 5 orders are for the same shop but haven't confirmed yet.

**Comment by shahthepro** [comment]
This is fixed and Have rerun those failed jobs
